// FEEL FREE TO CHANGE THESE NAMES TO SOMETHING MORE APPROPRIATE

// GET = Redux Saga
// SET = Redux Store

const types = {
  GET_INITIAL_POKEMON: "GET_INITIAL_POKEMON",
  SET_INITIAL_POKEMON: "SET_INITIAL_POKEMON",

  GET_MORE_POKEMON: "GET_MORE_POKEMON",
  SET_MORE_POKEMON: "SET_MORE_POKEMON",

  GET_SPRITES: "GET_SPRITES",
  SET_SPRITES: "SET_SPRITES",

  GET_POKEMON_DETAILS: "GET_POKEMON_DETAILS",
  SET_POKEMON_DETAILS: "SET_POKEMON_DETAILS",
  
  RETRIEVAL_ERROR: "RETRIEVAL_ERROR"
}

export default types